### ISSUE TITLE
Direct download link for OpenJDK

### ISSUE THREAD

**Issue by balivo** [MicrosoftDocs/xamarin-docs.pt-br#22]
Direct download link from Microsoft OpenJDK been removed?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Distribuição do Mobile OpenJDK da Microsoft - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/get-started/installation/openjdk#feedback)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1568](https://github.com/MicrosoftDocs/xamarin-docs/issues/1568) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @balivo

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/1568

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
